<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td>
                <h3 class="icon-head head-blog">
                    <?php echo Mage::helper('stuntcoders_damagecontrol')->__('Damage Control'); ?>
                </h3>
            </td>
        </tr>
    </table>
</div>
<?php  echo $this->getLayout()->createBlock('stuntcoders_damagecontrol/index_grid')->toHtml(); ?>
