<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td>
                <h3 class="icon-head head-blog">
                    <?php echo Mage::helper('stuntcoders_damagecontrol')->__('Review for order <a href="%s">#%s</a>', $this->getOrderUrl(), $this->getReview()->getOrder()->getIncrementId()); ?>
                </h3>
            </td>
            <td class="a-right">
                <?php echo $this->getChildHtml('damagecontrol.view'); ?>
            </td>
        </tr>
    </table>
</div>
<div>
    <div class="box-left">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-account"><?php echo $this->__('Review info:'); ?></h4>
            </div>
            <div class="fieldset">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Id:'); ?></label></td>
                            <td class="value"><strong><?php echo $this->getReview()->getId(); ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Send date:'); ?></label></td>
                            <td class="value"><strong><?php echo $this->getReview()->getSendingDate(); ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Reading Date:'); ?></label></td>
                            <td class="value"><strong><?php  echo $this->getReview()->getReadingDate() ? $this->getReview()->getReadingDate() : '-'; ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Mark:'); ?></label></td>
                            <td class="value"><strong><?php echo $this->getReview()->getMark() != 0 ? $this->getReview()->getMark() : '-'; ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Review Date:'); ?></label></td>
                            <td class="value"><strong><?php echo $this->getReview()->getReviewDate() ? $this->getReview()->getReviewDate() : '-'; ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Page visits:'); ?></label></td>
                            <td class="value"><strong><?php echo $this->getReview()->getVisits(); ?></strong></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="box-right">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-account"><?php echo $this->__('Customer info:'); ?></h4>
            </div>
            <div class="fieldset">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Name:'); ?></label></td>
                            <td class="value"><strong><?php echo $this->getCustomerName(); ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo $this->__('Email:'); ?></label></td>
                            <td class="value"><strong><?php echo $this->getCustomerEmail(); ?></strong></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <div class="box-left">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-account"><?php echo $this->__('Comment:'); ?></h4>
            </div>
            <div class="fieldset">
                <?php echo $this->getReview()->getComment() !== '' ? $this->escapeHtml($this->getReview()->getComment()) : $this->__('-- No comment --'); ?>
            </div>
        </div>
    </div>
</div>
