<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td>
                <h3 class="icon-head head-blog">
                    <?php echo Mage::helper('stuntcoders_damagecontroll')->__('Damage Controll'); ?>
                </h3>
            </td>
        </tr>
    </table>
</div>
<?php  echo $this->getLayout()->createBlock('stuntcoders_damagecontroll/index_grid')->toHtml(); ?>